### ISSUE TITLE
TypeError: xml.replace is not a function

### ISSUE THREAD

**Issue by lars-sorensen** [alabianca/xml-to-json#10]
When using it in VueJS, I get the following error
`cleanXML.js?95d7:3 Uncaught (in promise) TypeError: xml.replace is not a function`

**Comment by alabianca** [comment]
@lars-sorensen Can you provide a minimal repro code base where this is happening? Or a snapshot of your code that is causing this? `xml.replace` is just a string replacement function. where xml is the string.

```javascript
// remove unnecessary tags on the xml string to make conversion easier
module.exports = function cleanXML(xml) {
    return xml.replace(/>\s*</g, '><') //remove white spaces between elements
                .replace(/<\?xml.*\?>/g, '') //remove the root element
                .replace(/<!--.*-->/g,'') //remove comments
                .replace(/>\s*/g, '>') // remove any white spaces at the end of the xml string if any
                .replace(/\s*</g, '<') // remove any white spaces that are left at the beginning of the xml string
    
    
}
```

Are you using `createStream` or `xmlToJson` with the callback? `createStream` should cause issues in the front end since it relies on Node.js Buffer``
